apiVersion: v1
kind: Service
metadata:
  name: sample-api-service
  namespace: api
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  type: NodePort
  selector:
    app: "api"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80